#!/usr/bin/env php
<?php
declare(strict_types=1);

use Symfony\Component\Console\Application;
use \TestSeparator\Command\SeparateTestsCommand;
use \TestSeparator\Handler\TestsSeparatorFactory;
use \TestSeparator\Handler\ConfigurationFactory;
use \TestSeparator\Service\ConfigurationValidator;
use TestSeparator\Service\Logger;

require 'vendor/autoload.php';

$application = new Application();

$logger = new Logger();

try {
    // TODO use standard symfony configuration
    $configArray = ConfigurationFactory::makeConfigurationArrayByFile('config/test_separator.yml');
    $configuration = ConfigurationFactory::makeConfiguration($configArray, new ConfigurationValidator($logger));

    $testsSeparator = TestsSeparatorFactory::makeTestsSeparator($configuration, $logger);

    $application->add(new SeparateTestsCommand($testsSeparator, 'separate'));

    $application->run();
} catch (Exception $e) {
    $logger->error($e->getMessage());
}
