#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use \TestSeparator\Command\SeparateTestsCommand;
use \TestSeparator\Handler\SeparateTestsHandler;
use \TestSeparator\Handler\FileSystemHelper;
use \TestSeparator\Handler\DirectoryDeepService;
use \TestSeparator\Handler\ServicesSeparateTestsFactory;

$autoloadPaths = [
    __DIR__ . '/../../autoload.php',
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/vendor/autoload.php'
];

foreach ($autoloadPaths as $path) {
    if (file_exists($path)) {
        require_once $path;
    }
}

$application = new Application();

$fileSystemHelper = ServicesSeparateTestsFactory::makeFileSystemHelper(FileSystemHelper::class);
$levelDeepHelper = ServicesSeparateTestsFactory::makeLevelDeepService(DirectoryDeepService::class);

$separateHelper = new SeparateTestsHandler($fileSystemHelper,$levelDeepHelper);

$application->add(new SeparateTestsCommand($separateHelper,'separate'));

$application->run();
