#!/usr/bin/env php
<?php
declare(strict_types=1);

use Symfony\Component\Console\Application;
use \TestSeparator\Command\SeparateTestsCommand;
use \TestSeparator\Handler\SeparateTestsHandler;
use \TestSeparator\Handler\ServicesSeparateTestsFactory;
use \TestSeparator\Handler\ConfigurationFactory;
use TestSeparator\Service\Logger;

require 'vendor/autoload.php';

$application = new Application();

try {
    // TODO use standard symfony configuration
    $configuration = ConfigurationFactory::makeConfiguration('config/test_separator.yml');

    $logger = new Logger();
    $separateHandler = new SeparateTestsHandler(
        ServicesSeparateTestsFactory::makeTestFilePathHelper($configuration),
        ServicesSeparateTestsFactory::makeLevelDeepService($configuration->getDepthLevel()),
        $configuration->getResultPath(),
        $logger
    );

    $application->add(new SeparateTestsCommand($separateHandler, 'separate'));

    $application->run();
} catch (Exception $e) {
    echo $e->getMessage() . PHP_EOL;
}
